# Generated by Django 4.0.4 on 2022-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempADD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='num1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='num2',
            field=models.CharField(max_length=10),
        ),
    ]
