# Generated by Django 4.0.4 on 2022-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempADD', '0002_alter_calculate_num1_alter_calculate_num2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculate',
            name='output',
        ),
        migrations.AlterField(
            model_name='calculate',
            name='num1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='num2',
            field=models.IntegerField(),
        ),
    ]
