# Generated by Django 4.0.4 on 2022-05-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempADD', '0003_remove_calculate_output_alter_calculate_num1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='field_sum',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
