# Generated by Django 4.0.4 on 2022-05-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TempADD', '0004_calculate_field_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculate',
            old_name='field_sum',
            new_name='output',
        ),
    ]
